# 1. Database Connection URL
spring.datasource.url=jdbc:postgresql://dpg-d8s2764m0tmc739t7510-a:5432/stafflaunch

# 2. Credentials
spring.datasource.username=admin
spring.datasource.password=HoGcdeLBbs7wulkwOln6U4Era1HFzLDy

# 3. PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Hibernate Configuration (Crucial for Persistence)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 5. Console Output (Optional, good for debugging)
spring.jpa.show-sql=true